# Datos de conexión a MySQL (cámbialos según tu equipo)
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/sisbar?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
db.usuario=root
db.contrasena=17052004Os
